title: "Braden Crosson"
description: "Plant Breeding • Chemistry • Engineering"
theme: minima
url: "https://bradencrosson.com"   # fine even before custom domain
author: "Braden Crosson"

# Show specific pages in the top navigation
header_pages:
  - about.md
  - projects.md

minima:
  social_links:
    - { platform: github,   user_url: "https://github.com/bradencrosson" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/braden-crosson-0268a7378" }  # adjust if needed
    - { platform: email,    user_url: "mailto:braden@bradencrosson.com" }
